version: '3'
services:
  brand_service:
    build: ./brand_service
    container_name: brand_service
    ports:
      - "5001:5001"

  verify_service:
    build: ./verify_service
    container_name: verify_service
    ports:
      - "5002:5002"
    depends_on:
      - brand_service
